lovestory/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from misslove.views import articles, comments, users

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),

    url(r'^$', 'misslove.views.articles.homepage', name='homepage'),
    url(r'^accounts/signup/$', 'misslove.views.users.user_signup', name='signup'),
    url(r'^accounts/login/$', 'misslove.views.users.user_login', name="login"),
	url(r'^accounts/logout/$', 'misslove.views.users.user_logout', name='logout'),
	url(r'^accounts/info/(?P<user_id>\d+)/$', 'misslove.views.users.user_info', name="user_info"),
    url(r'^accounts/edit/(?P<user_id>\d+)/$', 'misslove.views.users.info_edit', name="info_edit"),
	url(r'^accounts/changepasswd/(?P<user_id>\d+)/$', 'misslove.views.users.change_password', name='change_password'),
	
	url(r'^articles/new$','misslove.views.articles.new_article', name="new_article"),
    url(r'^articles/catalog/(?P<article_type>\d+)/$', 'misslove.views.articles.article_catalog', name="article_catalog"),
	url(r'^articles/detail/(?P<article_id>\d+)/$', 'misslove.views.articles.article_detail', name="article_detail"),
    url(r'^articles/delete/(?P<article_id>\d+)/$', 'misslove.views.articles.article_delete', name="article_delete"),
    url(r'^articles/edit/(?P<article_id>\d+)$', 'misslove.views.articles.article_edit', name="article_edit"),

	url(r'^comments/add/(?P<article_id>\d+)/$','misslove.views.comments.comment_add', name="add_comment"),
    url(r'^comments/delete/(?P<comment_id>\d+)/$','misslove.views.comments.comment_delete', name="comment_delete"),
    url(r'^comments/edit/(?P<comment_id>\d+)/$','misslove.views.comments.comment_edit', name="comment_edit"),


]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misslove/models.py
# -*- coding: UTF-8 -*-

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.


class Article(models.Model):
	class Meta:
		verbose_name = u'文章'
		verbose_name_plural = u'文章'

	article_type = (
		(1, u'失恋'),
		(2, u'暗恋'),
		(3, u'异地恋'),
		(4, u'爱恋'),
	)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField(u'文章标题',max_length=200)
	text = models.TextField(u'文章内容')
	choose_type = models.IntegerField(u'板块选择',choices=article_type, default=article_type[0][0])
	created_time = models.DateTimeField(u'发布时间',default=timezone.now, editable=False)
	# article valid or invalid
	status = models.IntegerField(u'状态',default=1)
	image = models.ImageField(u'文章图片',upload_to='images/articleimg', blank=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	class Meta:
		verbose_name = u'评论'
		verbose_name_plural = u'评论'

	article = models.ForeignKey(Article)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	content = models.TextField()
	comment_time = models.DateTimeField(default=timezone.now,editable=False)
	# comment is valid or invalid
	status = models.IntegerField(default=1)

	def __unicode__(self):
		return self.article.title + '_' + self.author.username


class NewUser(AbstractUser):
	sex_choice = (
		('f', u'女'),
		('m', u'男'),
		('o', u'其他'),
	)
	love_status = (
		(1, u'失恋'),
		(2, u'暗恋'),
		(3, u'异地恋'),
		(4, u'爱恋'),
	)
	gender = models.CharField(u'性别', max_length=1, choices=sex_choice, default=sex_choice[0][0])
	whats_up = models.CharField(u'个性签名', max_length=50, default=u'这个人什么都没留下哦')
	status = models.IntegerField(u'恋爱状态', choices=love_status, default=love_status[0][0])
	avatar = models.ImageField(u'头像', upload_to='images/useravatar', blank=True)

	def get_avatar(self):
		if self.avatar and hasattr(self.avatar, 'url'):
			return self.avatar.url
		else:
			return '/static/misslove/img/default_avatar.jpg'

	def __unicode__(self):
		return self.username

misslove/forms.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
from misslove.models import NewUser, Article, Comment
from django.contrib.auth import get_user_model
from django.contrib.auth import login, authenticate
from django.shortcuts import get_object_or_404


class NewArticleForm(forms.ModelForm):
	class Meta:
		model = Article
		fields = ('title', 'text', 'choose_type', 'image',)


class UserForm(UserCreationForm):
	class Meta():
		model = get_user_model()
		fields = ('username', 'email', 'status')
		lables = {
			'username': u'用户名',
			'email': u'邮箱',
			'status': u'恋爱状态',
		}

class InfoEdit(forms.ModelForm):
	class Meta():
		model = get_user_model()
		fields = ('username','email', 'gender', 'whats_up', 'avatar','status')


class CommentAdd(forms.ModelForm):
	class Meta():
		model = Comment
		fields = ('content', )

class ChangePasswordForm(forms.Form):
	password_current = forms.CharField(label='当前密码',widget=forms.PasswordInput)
	password_new = forms.CharField(label='新密码', widget=forms.PasswordInput)
	password_again = forms.CharField(label='重复密码', widget=forms.PasswordInput)


class LoginForm(forms.Form):
	username = forms.CharField(max_length=255, required=True)
	password = forms.CharField(widget=forms.PasswordInput, required=True)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username = username, password = password)
		if user is not None:
			if not user.is_active:
				raise forms.ValidationError(u'抱歉,您已被管理员拉黑,请联系管理员')
		else:
			raise forms.ValidationError(u'用户名与密码不匹配,请重试')
		return self.cleaned_data

	def login(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password = password)
		return user

misslove/views.py
from django.shortcuts import render

# Create your views here.

misslove/views/articles.py
# coding=UTF-8
from django.shortcuts import render,redirect, get_object_or_404
from misslove.models import Article, NewUser, Comment
from django.shortcuts import render_to_response
from django.template import RequestContext
from misslove.forms import NewArticleForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
def homepage(request):
	template_name = 'misslove/homepage.html'

	article_total = float(Article.objects.filter(status=1).count())
	article_data = []
	user_total = float(NewUser.objects.filter(is_active=True).count())
	user_data = []
	if article_data == 0:
		article_data = 1
	if user_total == 0:
		user_total = 1
	for i in range(1,5):
		article_data.append(round(float(Article.objects.filter(status=1).filter(choose_type=i).count())/article_total, 1))
		user_data.append(round(float(NewUser.objects.filter(is_active=True).filter(status=i).count())/user_total, 1))

	return render(request, template_name,
				  {"article_data": article_data, "user_data": user_data,})


@login_required
def new_article(request):
	template_name = 'misslove/new_article.html'
	if request.method == "POST":
		form = NewArticleForm(request.POST, request.FILES)
		if form.is_valid():
			#img_file = request.FILES['image']
			article = form.save(commit=False)
			#article.image = img_file
			article.author = request.user
			article.save()
			messages.success(request, u'发布文章成功')
			return redirect('article_detail', article_id=article.id)
	else:
		form = NewArticleForm()
	return render(request,template_name, {'form':form})


def article_catalog(request, article_type):
	template_name = 'misslove/article_catalog.html'
	limit = 10
	articles = Article.objects.filter(status=1).filter(choose_type=article_type).order_by('-created_time')
	article_type = Article.article_type[int(article_type)-1][1]
	paginator = Paginator(articles, limit)
	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)
	return render_to_response(template_name,
							  {'articles': articles, 'article_type': article_type},
							  context_instance=RequestContext(request))


def article_detail(request, article_id):
	template_name = 'misslove/article_detail.html'
	article = get_object_or_404(Article, id=article_id)
	comments = article.comment_set.filter(status=1).order_by('-comment_time')
	return render_to_response(template_name,
							  {'article': article, 'comments':comments},
							  context_instance=RequestContext(request))							  


@login_required
def article_delete(request, article_id):
	article = get_object_or_404(Article, id = article_id)
	article.status = 0
	article.save()
	messages.success(request, u'成功删除文章')
	return redirect('user_info',user_id = request.user.id )


@login_required
def article_edit(request, article_id):
	article = get_object_or_404(Article, id = article_id)
	if request.method == "POST":
		form = NewArticleForm(request.POST, request.FILES, instance=article)
		if form.is_valid():
			article = form.save(commit=False)
			article.author = request.user
			article.save()
			messages.success(request, u'文章编辑成功')
			return redirect('article_detail',article_id=article_id)
	else:
		form = NewArticleForm(instance=article)
	return render(request, 'misslove/new_article.html', {'form':form})

misslove/views/comments.py
# coding:UTF-8
from django.shortcuts import render
from misslove.models import Comment, Article
from django.contrib.auth.decorators import login_required
from misslove.forms import CommentAdd
from django.shortcuts import get_object_or_404,redirect
from django.contrib import messages

# Create your views here.


@login_required
def comment_add(request, article_id):
	form = CommentAdd(request.POST)
	if form.is_valid():
		ca = form.save(commit=False)
		ca.author = request.user
		ca.article = get_object_or_404(Article, id = article_id)
		ca.save()
		messages.success(request, u'评论添加成功')
		return redirect('article_detail', article_id=article_id)
	else:
		return redirect('article_detail', article_id=article_id)


@login_required
def comment_delete(request, comment_id):
	#article = get_object_or_404(Article, id = article_id)
	comment = get_object_or_404(Comment, id = comment_id)
	comment.status = 0
	comment.save()
	messages.success(request, u'评论删除成功')
	return redirect('user_info',user_id = request.user.id)


@login_required
def comment_edit(request, comment_id):
	comment = get_object_or_404(Comment, id = comment_id)
	if request.method == 'POST':
		form = CommentAdd(request.POST, instance= comment)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.author = request.user
			comment.save()
			messages.success(request, u'评论编辑成功')
			return redirect('article_detail', article_id = comment.article.id)
	else:
		form = CommentAdd(instance=comment)
	return render(request,'misslove/edit_comment.html', {'form':form})

misslove/views/users.py
# coding:UTF-8
from django.shortcuts import get_object_or_404,render_to_response,redirect
from django.template import RequestContext
from misslove.models import NewUser, Article, Comment
from misslove.forms import UserForm, InfoEdit, ChangePasswordForm, LoginForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages,auth


def user_login(request):
	template_name= 'misslove/user_login.html'
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			user = form.login()
			if user:
				login(request, user)
				messages.success(request, u'成功登录')
				return redirect('homepage')
	else:
		form = LoginForm()
	return render_to_response(template_name,
							  {'form': form,},
							  context_instance=RequestContext(request))


@login_required
def user_logout(request):
	auth.logout(request)
	messages.success(request, u'成功退出')
	return redirect('homepage')


@login_required
def user_info(request, user_id):
	template_name = "misslove/user_info.html"
	current_user = get_object_or_404(NewUser, id = user_id)
	user_articles = current_user.article_set.filter(status=1).order_by('created_time')[:9]
	user_comments = current_user.comment_set.filter(status=1).order_by('comment_time')[:9]
	return render_to_response(template_name,
							  {'current_user':current_user,'user_articles':user_articles,
							   'user_comments':user_comments},
							  context_instance=RequestContext(request))


def user_signup(request):
	template_name = "misslove/user_signup.html"
	if request.method == "POST":
		uf = UserForm(request.POST)
		if uf.is_valid():
			user_name = request.POST.get('username')
			password = uf.clean_password2()
			love_status = request.POST.get('status')
			uf.save()
			user = authenticate(username = user_name, password = password)
			if user.is_active:
				user.status = love_status
				login(request,user)
				messages.success(request,u'注册成功并登录')
			return redirect('homepage')
	else:
		uf = UserForm
	return render_to_response(template_name,
							  {'user_form':uf },
							  context_instance=RequestContext(request))


@login_required
def info_edit(request, user_id):
	user = get_object_or_404(NewUser, id = user_id)
	if request.user == user:
		if request.method == 'POST':
			ifed = InfoEdit(request.POST, request.FILES, instance=user)
			if ifed.is_valid():
				user = ifed.save()
				messages.success(request, u'资料修改成功')
				return redirect('user_info', user_id = user_id)
		else:
			ifed = InfoEdit(instance=user)
	else:
		return redirect('homepage')
	return render_to_response('misslove/infoedit.html',
							  {'info_form': ifed, 'current_user':user},
							  context_instance=RequestContext(request))


@login_required
def change_password(request, user_id):
	error = []
	user = get_object_or_404(NewUser, id = user_id)
	if request.method == 'POST':
		form = ChangePasswordForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			user = authenticate(username=user.username,password=data['password_current'])
			if user is not None:
				if data['password_new'] == data['password_again']:
					user = get_object_or_404(NewUser, id = user_id)
					user.set_password(data['password_new'])
					user.save()
					messages.success(request, u'密码修改成功')
					return redirect('login')
				else:
					error.append("两次输入密码不一样")
			else:
				error.append("请输入正确的旧密码")
	else:
		form = ChangePasswordForm()
	return render_to_response('misslove/change_password.html',{'form':form,'error':error},
							  context_instance=RequestContext(request))

templates/misslove/article_catalog.html
{% extends "misslove/base.html" %}

{% block title %}{{ article_type }}{% endblock %}

{% block content %}
    <!--板块名字-->
    <div class="page-header" xmlns="http://www.w3.org/1999/html">
        <h1>
            {{ article_type }}
            {% if article_type == "失恋"%}
                <small>人生若只如初见,何事秋风悲画扇</small>
            {% elif article_type == "暗恋" %}
                <small>山有木兮木有枝，吾悦君兮君不知</small>
            {% elif article_type == "异地恋" %}
                <small>两情若是久长时，又岂在朝朝暮暮</small>
            {% elif article_type == "爱恋" %}
                <small>开辟鸿蒙，谁为情种？都只为风月情浓</small>
            {% endif %}

        </h1>
    </div>

    <!--本版块没有人发布文章-->
    {% ifequal articles.paginator.count 0%}
        <div class="no-article">
             <p>{{ article_type }}版区现在还没有任何人发帖哦，赶快去发布吧</p>
        </div>
    <!--本板块有人发布文章-->
    {% else %}
        {% for article in articles.object_list %}
            <div class="one-article">
            <h1>{{article.title  }}</h1>

                <div class="article-meta">
                    <span class="author">作者：<a href="/accounts/info/{{ article.author.id }}">{{ article.author }}</a></span> &bull;
                    <time class="post-date" datetime="{{ article.created_time }}" title=" {{ article.created_time }}">{{ article.created_time }}</time>
                </div>

                <div>
                    {{ article.text | safe | truncatechars_html:40 }}
                </div>

                <a href="/articles/detail/{{ article.id }}" class="btn btn-default">阅读全文</a>
            </div>
        {% endfor %}
    {% endifequal %}

    {% ifnotequal articles.paginator.num_pages 1 %}

    <nav>
        <ul class="pagination">

        <li {% if not articles.has_previous %}class="disabled"{% endif %}>
            <a {% if articles.has_previous %}href="?page={{ articles.previous_page_number }}"
               {% endif %}
               aria-label="上一页">
            <span aria-hidden="true">&laquo;</span></a>
        </li>

        {% for page_number in articles.paginator.page_range %}
            {% ifequal page_number articles.number %}
                <li class="active">
                    <a href="#">{{ page_number }}<span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endifequal %}
        {% endfor %}

        <li {% if not articles.has_next %}class="disabled"{% endif %}>
            <a {% if articles.has_next %}href="?page={{ articles.next_page_number }}"
               {% endif %}aria-label="下一页">
            <span aria-hidden="true">&raquo;</span></a>
        </li>

        </ul>
    </nav>
    {% endifnotequal %}

{% endblock %}

templates/misslove/article_detail.html
{% extends "misslove/base.html" %}
{% load staticfiles %}

{% block title %}{{ article }}{% endblock %}

{% block content %}
    <div>
    <!--文章内容-->
        <div class="article-box">
               <div>
                   <span id="article-detail-title">{{ article.title }}</span>

                   </div>

               <!--
               <img id="avatar_detail" src="{{ article.author.get_avatar }}" alt="{{ article_author }}" title="{{ article_author }}"/>
                -->
              <div class="article-meta">
            <p>
            <span class="author">
                <img id="avatar_detail" src="{{ article.author.get_avatar }}" alt="{{ article_author }}" title="{{ article_author }}"/>
                <a href="/accounts/info/{{ article.author.id }}">{{ article.author }}</a>
            </span> &bull;
            <time class="post-date" datetime=" {{ article.created_time }}" title=" {{ article.created_time }}"> {{ article.created_time }}</time> &nbsp;
        <span id="article-detail-type">所属板块：<a href="/articles/catalog/{{ article.choose_type }}">{{ article.get_choose_type_display }}</a></span>
            </p>
        </div>

            <div>
                {% autoescape off %}
                    {{ article.text  }}
                {% endautoescape %}
            </div>
            {% if article.image %}
                <img id ="article-detail-img" src="{{ article.image.url }}" alt="{{ article }}" title="{{ article }}"/>
            {% endif %}
            {% if article.author.id == user.id %}
                <div id="article-detail-edit-delete">
                <a href="/articles/edit/{{ article.id }}" data-toggle="tooltip" data-placement="top" title="编辑文章">
                    <span class="glyphicon glyphicon-pencil"></span></a>
                <a href="/articles/delete/{{ article.id }}" data-toggle="tooltip" data-placement="bottom" title="删除文章"><span class="glyphicon glyphicon-trash"></span></a>
                </div>
            {% endif %}
        </div>
    </div>

    <!--文章评论-->
    <h4>评论区</h4>
    <div class="comment-box" id="comment_box">
    {% if comments|length == 0%}
        <p>暂时没有评论哦,赶紧添加吧～</p>
    {% else %}
    {% for comment in comments %}
        <hr/>
        <div id="comment_{{ comment.id }}">
       <!-- <p>#{{ forloop.counter }}</p> -->

            <!--
            <p><a href="/accounts/info/{{ comment.author.id }}">{{ comment.author }}</a>
        {{ comment.comment_time }}</p>
        -->

              <div class="article-meta">
            <p>
            <span class="author">
                <img id="avatar_detail" src="{{ comment.author.get_avatar }}" alt="{{ comment_author }}" title="{{ comment_author }}"/>
                <a href="/accounts/info/{{ comment.author.id }}">{{ comment.author }}</a>
            </span> &bull;
            <time class="post-date" datetime=" {{ comment.comment_time }}" title=" {{ comment.comment_time }}"> {{ comment.comment_time }}</time>
        </p>
        </div>


        <div>{{ comment.content | safe}}</div>

        {% if user.id == article.author.id or user.id == comment.author.id %}
            <div>
            <a href="/comments/edit/{{ comment.id }}" data-toggle="tooltip" data-placement="top" title="编辑评论">
                <span class="glyphicon glyphicon-pencil"></span></a>
            <a href="/comments/delete/{{ comment.id }}" data-toggle="tooltip" data-placement="bottom" title="删除评论">
                <span class="glyphicon glyphicon-trash"></span></a>
            </div>
        {% endif %}
        </div>
    {% endfor %}
    {% endif %}
    </div>

    <div>
    {% if user.is_authenticated %}

        <form class="comment-add" action="/comments/add/{{ article.id }}/" method="POST">
            {% csrf_token %}
            <label for="content">添加评论：</label>
            <textarea rows="6" name="content" placeholder="请在此输入评论"></textarea>
            <input type="submit" name="submit" value="提交" class="btn btn-default"/>
        </form>
    {% else %}
        <div class="comment-login">
        <p>登录才可以评论哦</p>
        </div>

    {% endif %}
    </div>


 <script type="text/javascript">
  if(document.getElementById("comment_box").clientHeight>2000)
  {
      document.getElementById("comment_box").style.height="2000px";
      document.getElementById("comment_box").style.overflowY="scroll";
  }

 </script>

{% endblock %}

templates/misslove/edit_comment.html
{% extends 'misslove/base.html' %}
{% block title %}编辑评论{% endblock %}
{% block content %}
    <div class="comment-edit">
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-default">保存</button>
    </form>
    </div>
{% endblock %}

templates/misslove/infoedit.html
{% extends 'misslove/base.html' %}

{% block title %}编辑个人资料{% endblock %}

{% block content %}
    <div class="info-edit">

     <h3>编辑个人信息</h3>
    <form enctype="multipart/form-data" method="POST" role="form">
		{% csrf_token %}

             <div class="form-group">
            <label for="id_username">用户名:</label>
            <input id="id_username" maxlength="30" name="username" type="text" value="{{ current_user }}" class="form-control"/>
            <span class="helptext help-block">必填。不多于30个字符。只能用字母、数字和字符 @/./+/-/_ 。</span>
            </div>


        <div class="form-group">
            <label for="id_email">电子邮件地址:</label>
            <input id="id_email" maxlength="254" name="email" type="email" value="{{ current_user.email }}" class="form-control"/>
        </div>


        <div class="form-group">
            <label for="id_gender">性别:</label>
            <select id="id_gender" name="gender" class="form-control">
                {% for sex in current_user.sex_choice %}
                    <option value="{{ sex.0 }}" {% if sex.0 == current_user.gender %}selected{% endif %}>
                    {{ sex.1 }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="id_status">恋爱状态:</label>
            <select id="id_status" name="status" class="form-control">
                {% for lstatus in current_user.love_status %}
                    <option value="{{ lstatus.0 }}" {% if lstatus.0 == current_user.status %}selected{% endif %}>
                    {{ lstatus.1 }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="id_whats_up">个性签名:</label>
            <input id="id_whats_up" maxlength="50" name="whats_up" type="text" value="{{ current_user.whats_up }}" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="id_avatar">当前头像:</label>
             <img class="avatar-edit" src="{{ current_user.get_avatar }}"/>
        {% ifnotequal current_user.get_avatar '/static/misslove/img/default_avatar.jpg' %}
            <input id="avatar-clear_id" name="avatar-clear" type="checkbox" />
            <label for="avatar-clear_id">删除头像</label><br />
        {% endifnotequal %}
        </div>
        <div class="form-group">
                <label for="id_avatar">修改头像:</label>
             <input id="id_avatar" name="avatar" type="file" />

        </div>
		<button type="submit" class="btn btn-default">Save</button>



	</form>

    </div>

{% endblock %}


<!--


<table class="table">
  ...
</table>

-->

templates/misslove/user_info.html
{% extends 'misslove/base.html' %}
{% load staticfiles %}

{% block title %}{{ current_user.username }}的信息{% endblock %}

{% block extracss %}
<style type="text/css">

</style>
{% endblock %}

{% block content %}

<div class="row no-js">

    <div id="user-info-top">
        <img src="{% static 'misslove/img/userInfo.jpg'%}" id="user-info-bg">
        <div id = "user-info-detail">
            <img src="{{ current_user.get_avatar }}" alt="{{ current_user.username }}"
                 title="{{ current_user.username }}" class="img-thumbnail img-circle avatar"/>
            <p id="user-info-username">{{ current_user.username }}</p>

            <p>{{ current_user.whats_up }}</p>
            <p>
                <span class="glyphicon glyphicon-heart"></span>&nbsp;<span>{{ current_user.get_status_display }}</span>
                &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user"></span>&nbsp;<span id="userInfo-gender">{{ current_user.get_gender_display }}</span>
                &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-envelope"></span>&nbsp;<span id="userInfo-email">{{ current_user.email }}</span>
            </p>

        </div>
        <div id = "user-info-edit-link">
            {% ifequal current_user.id user.id %}
                <a href="/accounts/edit/{{ current_user.id }}" class="btn btn-default">编辑资料</a>
              <a href="/accounts/changepasswd/{{ current_user.id }}" class="btn btn-default">修改密码</a>
            {% endifequal %}
        </div>
    </div>

    <div id="tabs">

        <ul class="menu0" id="menu0">
            <li onclick="setTab(0,0)" class="hover">文章（共{{ user_articles | length }}篇）</li>
            <li onclick="setTab(0,1)">评论（共{{ user_comments|length }}条）</li>
        </ul>

        <div class="main" id="main0">

        <div class="block">

        {% ifequal user_articles|length 0 %}
            <P>对不起，你还没有发表过任何文章哦</P>
        {% else %}
            <ul class="list-group">
            {% for user_article in user_articles %}
                <li class="list-group-item">
                <a href="/articles/detail/{{ user_article.id }}">{{ user_article }}</a>&nbsp;&nbsp;
                    {% ifequal current_user.id user.id %}
                    <a href="/articles/delete/{{ user_article.id }}" class="badge" data-toggle="tooltip" data-placement="left" title="删除文章">
                        <span class="glyphicon glyphicon-remove"></span></a>
                    {% endifequal %}
                </li>
            {% endfor %}
            </ul>
        {% endifequal %}
        </div>

        <div>
        {% ifequal user_comments|length 0 %}
            <P>对不起，你还没有发表过任何评论哦</P>
        {% else %}
            <ul class="list-group">
            {% for user_comment in user_comments %}
                <li class="list-group-item">
                   <a href="/articles/detail/{{ user_comment.article.id }}/#comment_{{ user_comment.id }}">
                       {{ user_comment.article.title }}</a>&nbsp;&nbsp;
                    {% if current_user.id == user.id or user.id == comment.article.author.id %}
                    <a href="/comments/delete/{{ user_comment.id }}" class="badge">
                        <span class="glyphicon glyphicon-remove"></span></a>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        {% endifequal %}
        </div>

        </div>

    </div>

</div>
{% endblock %}


{% block extrajs %}
    <script>
    function setTab(m,n){
    var tli=document.getElementById("menu"+m).getElementsByTagName("li");
    var mli=document.getElementById("main"+m).getElementsByTagName("div");
    for(i=0;i<tli.length;i++){
    tli[i].className=i==n?"hover":"";
    mli[i].style.display=i==n?"block":"none";
    }
    }
    </script>
{% endblock %}